// <auto-generated />
namespace NJCSC.App.Repository.poc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class c10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(c10));
        
        string IMigrationMetadata.Id
        {
            get { return "202103251911412_c10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
